export const data = [
    {
        id : 1,
        name : "Focal Clear Headphones",
        description : "The best detail, resolution and dynamics in its...and almost any other price range",
        img : 'https://i.ibb.co/r0K8BCC/233524-0-s8gtuy.png',
        price : 890.95,
        rating : 4.0,
        reviews : 40,
    },
    {
        id : 2,
        name : "Sennheiser HD 560S",
        description : "Elegant design and remarkable sound performance",
        img : 'https://i.ibb.co/PCQSPbF/rv1-Ad-U-headphones-free-download.png',
        price : 600.00,
        rating : 3.5,
        reviews : 15,
    },
    {
        id : 3,
        name : "Focal Stellia",
        description : "Hands-free, Hads-on Music Experience",
        img : 'https://i.ibb.co/r0K8BCC/233524-0-s8gtuy.png',
        price : 900.00,
        rating : 5.0,
        reviews : 60,
    },
    {
        id : 4,
        name : "Focal Clear Headphones",
        description : "The best detail, resolution and dynamics in its...and almost any other price range",
        img : 'https://i.ibb.co/r0K8BCC/233524-0-s8gtuy.png',
        price : 890.95,
        rating : 4.0,
        reviews : 40,
    },
    {
        id : 5,
        name : "Sennheiser HD 560S",
        description : "Elegant design and remarkable sound performance",
        img : 'https://i.ibb.co/PCQSPbF/rv1-Ad-U-headphones-free-download.png',
        price : 600.00,
        rating : 3.5,
        reviews : 15,
    },
    {
        id : 6,
        name : "Focal Stellia",
        description : "Hands-free, Hads-on Music Experience",
        img : 'https://i.ibb.co/r0K8BCC/233524-0-s8gtuy.png',
        price : 900.00,
        rating : 5.0,
        reviews : 60,
    },
    {
        id : 7,
        name : "Focal Clear Headphones",
        description : "The best detail, resolution and dynamics in its...and almost any other price range",
        img : 'https://i.ibb.co/r0K8BCC/233524-0-s8gtuy.png',
        price : 890.95,
        rating : 4.0,
        reviews : 40,
    },
    {
        id : 8,
        name : "Sennheiser HD 560S",
        description : "Elegant design and remarkable sound performance",
        img : 'https://i.ibb.co/PCQSPbF/rv1-Ad-U-headphones-free-download.png',
        price : 600.00,
        rating : 3.5,
        reviews : 15,
    },
    {
        id : 9,
        name : "Focal Stellia",
        description : "Hands-free, Hads-on Music Experience",
        img : 'https://i.ibb.co/r0K8BCC/233524-0-s8gtuy.png',
        price : 900.00,
        rating : 5.0,
        reviews : 60,
    },
    
]